### ISSUE TITLE
cargo build error 

### ISSUE THREAD

**Issue by cyl19970726** [mir-protocol/plonky2#1110]
When I building this project followed by steps described in the README file ,
```
rustup override set nightly

cd plonky2 

RUSTFLAGS=-Ctarget-cpu=native cargo run --release --example bench_recursion -- -vv
```
happened the below error:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
   Compiling plonky2_field v0.1.0 (/root/plonky2/field)
   Compiling clap v3.2.25
thread 'rustc' panicked at 'assertion failed: !self.intercrate', compiler/rustc_trait_selection/src/traits/query/evaluate_obligation.rs:100:13
stack backtrace:
   0:     0x7fa60c01fa81 - std::backtrace_rs::backtrace::libunwind::trace::h3c8b1207af9f7dc4
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fa60c01fa81 - std::backtrace_rs::backtrace::trace_unsynchronized::h6cc4d1ef12765b77
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fa60c01fa81 - std::sys_common::backtrace::_print_fmt::h4b58ac6692087093
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fa60c01fa81 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4cfe701aadad59ba
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fa60c085d8f - core::fmt::rt::Argument::fmt::h017682705ed0d628
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/core/src/fmt/rt.rs:138:9
   5:     0x7fa60c085d8f - core::fmt::write::h69b96bfc1fe292d1
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/core/src/fmt/mod.rs:1094:21
   6:     0x7fa60c0123c7 - std::io::Write::write_fmt::h320e7f56f42ea27f
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/io/mod.rs:1714:15
   7:     0x7fa60c01f895 - std::sys_common::backtrace::_print::h0061961dcfb0fc1f
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fa60c01f895 - std::sys_common::backtrace::print::h3caf3df7088e0a43
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fa60c022673 - std::panicking::default_hook::{{closure}}::h77ae45a48b0419f4
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/panicking.rs:269:22
  10:     0x7fa60c022404 - std::panicking::default_hook::h1750cbe688cc23cf
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/panicking.rs:288:9
  11:     0x7fa60f32ecab - rustc_driver_impl[c8224e60c583ce9e]::install_ice_hook::{closure#0}
  12:     0x7fa60c022e9e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2f7c4b5be15d65f3
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/alloc/src/boxed.rs:2024:9
  13:     0x7fa60c022e9e - std::panicking::rust_panic_with_hook::hb1e7052d584ca5b8
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/panicking.rs:709:13
  14:     0x7fa60c022be1 - std::panicking::begin_panic_handler::{{closure}}::haa7ba27cd61f2c57
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/panicking.rs:595:13
  15:     0x7fa60c01fee6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf9f1a9ff381b40f6
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/sys_common/backtrace.rs:151:18
  16:     0x7fa60c022972 - rust_begin_unwind
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/panicking.rs:593:5
  17:     0x7fa60c081fe3 - core::panicking::panic_fmt::h7ce7a976d3070fa0
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/core/src/panicking.rs:67:14
  18:     0x7fa60c082073 - core::panicking::panic::hc2792b9695c02495
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/core/src/panicking.rs:117:5
  19:     0x7fa60d5731fa - <rustc_trait_selection[41dd4520de8bf710]::traits::fulfill::FulfillProcessor as rustc_data_structures[c8b73cf51072de45]::obligation_forest::ObligationProcessor>::process_obligation
  20:     0x7fa60d564bf4 - <rustc_data_structures[c8b73cf51072de45]::obligation_forest::ObligationForest<rustc_trait_selection[41dd4520de8bf710]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[41dd4520de8bf710]::traits::fulfill::FulfillProcessor>
  21:     0x7fa60d722dff - <rustc_trait_selection[41dd4520de8bf710]::traits::engine::ObligationCtxt>::select_all_or_error
  22:     0x7fa60d6f87f7 - rustc_trait_selection[41dd4520de8bf710]::traits::specialize::translate_substs
  23:     0x7fa60d6e445b - rustc_trait_selection[41dd4520de8bf710]::traits::project::opt_normalize_projection_type
  24:     0x7fa60d8b930e - <rustc_infer[513a04dd9302731b]::infer::InferCtxt>::commit_if_ok::<rustc_trait_selection[41dd4520de8bf710]::traits::project::ProjectAndUnifyResult, rustc_infer[513a04dd9302731b]::traits::project::MismatchedProjectionTypes, rustc_trait_selection[41dd4520de8bf710]::traits::project::poly_project_and_unify_type::{closure#0}>
  25:     0x7fa60dfe9a08 - <rustc_trait_selection[41dd4520de8bf710]::traits::select::SelectionContext>::evaluate_predicate_recursively
  26:     0x7fa60dfe4eda - <rustc_trait_selection[41dd4520de8bf710]::traits::select::SelectionContext>::evaluate_root_obligation
  27:     0x7fa60dfe4bc0 - <core[39f2cadfad9b7192]::iter::adapters::map::Map<core[39f2cadfad9b7192]::iter::adapters::flatten::Flatten<core[39f2cadfad9b7192]::array::iter::IntoIter<&alloc[60c0f1c9ed75b84c]::vec::Vec<rustc_middle[a92143083d338f81]::ty::Predicate>, 2usize>>, rustc_trait_selection[41dd4520de8bf710]::traits::coherence::impl_intersection_has_impossible_obligation::{closure#1}> as core[39f2cadfad9b7192]::iter::traits::iterator::Iterator>::try_fold::<(), core[39f2cadfad9b7192]::iter::traits::iterator::Iterator::find::check<rustc_infer[513a04dd9302731b]::traits::Obligation<rustc_middle[a92143083d338f81]::ty::Predicate>, &mut rustc_trait_selection[41dd4520de8bf710]::traits::coherence::impl_intersection_has_impossible_obligation::{closure#0}>::{closure#0}, core[39f2cadfad9b7192]::ops::control_flow::ControlFlow<rustc_infer[513a04dd9302731b]::traits::Obligation<rustc_middle[a92143083d338f81]::ty::Predicate>>>
  28:     0x7fa60dfe39d1 - rustc_trait_selection[41dd4520de8bf710]::traits::coherence::overlap
  29:     0x7fa60e4e4c6b - <rustc_middle[a92143083d338f81]::traits::specialization_graph::Children as rustc_trait_selection[41dd4520de8bf710]::traits::specialize::specialization_graph::ChildrenExt>::insert
  30:     0x7fa60e4e2ec0 - <rustc_middle[a92143083d338f81]::traits::specialization_graph::Graph as rustc_trait_selection[41dd4520de8bf710]::traits::specialize::specialization_graph::GraphExt>::insert
  31:     0x7fa60e4e1a83 - rustc_trait_selection[41dd4520de8bf710]::traits::specialize::specialization_graph_provider
  32:     0x7fa60e71f17b - rustc_query_impl[7a314159d938cad9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a314159d938cad9]::query_impl::specialization_graph_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a92143083d338f81]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7fa60e71f151 - <rustc_query_impl[7a314159d938cad9]::query_impl::specialization_graph_of::dynamic_query::{closure#2} as core[39f2cadfad9b7192]::ops::function::FnOnce<(rustc_middle[a92143083d338f81]::ty::context::TyCtxt, rustc_span[c131c644fb7cb5fa]::def_id::DefId)>>::call_once
  34:     0x7fa60dfc3c66 - rustc_query_system[fcf123a786d6e0bc]::query::plumbing::try_execute_query::<rustc_query_impl[7a314159d938cad9]::DynamicConfig<rustc_query_system[fcf123a786d6e0bc]::query::caches::DefaultCache<rustc_span[c131c644fb7cb5fa]::def_id::DefId, rustc_middle[a92143083d338f81]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[7a314159d938cad9]::plumbing::QueryCtxt, true>
  35:     0x7fa60ec78fc6 - rustc_query_impl[7a314159d938cad9]::query_impl::specialization_graph_of::get_query_incr::__rust_end_short_backtrace
  36:     0x7fa60e6810b1 - rustc_hir_analysis[58a31f7655e3c3]::coherence::coherent_trait
  37:     0x7fa60dfca3b1 - rustc_query_impl[7a314159d938cad9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a314159d938cad9]::query_impl::coherent_trait::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a92143083d338f81]::query::erase::Erased<[u8; 0usize]>>
  38:     0x7fa60dfca391 - <rustc_query_impl[7a314159d938cad9]::query_impl::coherent_trait::dynamic_query::{closure#2} as core[39f2cadfad9b7192]::ops::function::FnOnce<(rustc_middle[a92143083d338f81]::ty::context::TyCtxt, rustc_span[c131c644fb7cb5fa]::def_id::DefId)>>::call_once
  39:     0x7fa60e9b73c3 - rustc_query_system[fcf123a786d6e0bc]::query::plumbing::try_execute_query::<rustc_query_impl[7a314159d938cad9]::DynamicConfig<rustc_query_system[fcf123a786d6e0bc]::query::caches::DefaultCache<rustc_span[c131c644fb7cb5fa]::def_id::DefId, rustc_middle[a92143083d338f81]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[7a314159d938cad9]::plumbing::QueryCtxt, true>
  40:     0x7fa60e9b6d3f - rustc_query_impl[7a314159d938cad9]::query_impl::coherent_trait::get_query_incr::__rust_end_short_backtrace
  41:     0x7fa60e76d433 - <rustc_session[ba0171e1a42d92f9]::session::Session>::track_errors::<rustc_hir_analysis[58a31f7655e3c3]::check_crate::{closure#3}, ()>
  42:     0x7fa60e76ad0e - rustc_hir_analysis[58a31f7655e3c3]::check_crate
  43:     0x7fa60e761dda - rustc_interface[6ebb3a637cfebd5]::passes::analysis
  44:     0x7fa60e7ef68a - rustc_query_impl[7a314159d938cad9]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7a314159d938cad9]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a92143083d338f81]::query::erase::Erased<[u8; 1usize]>>
  45:     0x7fa60e7ef679 - <rustc_query_impl[7a314159d938cad9]::query_impl::analysis::dynamic_query::{closure#2} as core[39f2cadfad9b7192]::ops::function::FnOnce<(rustc_middle[a92143083d338f81]::ty::context::TyCtxt, ())>>::call_once
  46:     0x7fa60eaea21f - rustc_query_system[fcf123a786d6e0bc]::query::plumbing::try_execute_query::<rustc_query_impl[7a314159d938cad9]::DynamicConfig<rustc_query_system[fcf123a786d6e0bc]::query::caches::SingleCache<rustc_middle[a92143083d338f81]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7a314159d938cad9]::plumbing::QueryCtxt, true>
  47:     0x7fa60eae9dc4 - rustc_query_impl[7a314159d938cad9]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  48:     0x7fa60e519455 - <rustc_middle[a92143083d338f81]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[c8224e60c583ce9e]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>>
  49:     0x7fa60e518a82 - <rustc_interface[6ebb3a637cfebd5]::interface::Compiler>::enter::<rustc_driver_impl[c8224e60c583ce9e]::run_compiler::{closure#1}::{closure#2}, core[39f2cadfad9b7192]::result::Result<core[39f2cadfad9b7192]::option::Option<rustc_interface[6ebb3a637cfebd5]::queries::Linker>, rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>>
  50:     0x7fa60e50f795 - rustc_span[c131c644fb7cb5fa]::set_source_map::<core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>, rustc_interface[6ebb3a637cfebd5]::interface::run_compiler<core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>, rustc_driver_impl[c8224e60c583ce9e]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  51:     0x7fa60e50f206 - <scoped_tls[8bf4edb3452830f]::ScopedKey<rustc_span[c131c644fb7cb5fa]::SessionGlobals>>::set::<rustc_interface[6ebb3a637cfebd5]::interface::run_compiler<core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>, rustc_driver_impl[c8224e60c583ce9e]::run_compiler::{closure#1}>::{closure#0}, core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>>
  52:     0x7fa60e50e7cc - std[fa0d0b5c306c9702]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6ebb3a637cfebd5]::util::run_in_thread_pool_with_globals<rustc_interface[6ebb3a637cfebd5]::interface::run_compiler<core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>, rustc_driver_impl[c8224e60c583ce9e]::run_compiler::{closure#1}>::{closure#0}, core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>>
  53:     0x7fa60e50e595 - <<std[fa0d0b5c306c9702]::thread::Builder>::spawn_unchecked_<rustc_interface[6ebb3a637cfebd5]::util::run_in_thread_pool_with_globals<rustc_interface[6ebb3a637cfebd5]::interface::run_compiler<core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>, rustc_driver_impl[c8224e60c583ce9e]::run_compiler::{closure#1}>::{closure#0}, core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[39f2cadfad9b7192]::result::Result<(), rustc_span[c131c644fb7cb5fa]::ErrorGuaranteed>>::{closure#1} as core[39f2cadfad9b7192]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  54:     0x7fa60c02d315 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h21ee91033946694b
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/alloc/src/boxed.rs:2010:9
  55:     0x7fa60c02d315 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdf07228f28997b56
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/alloc/src/boxed.rs:2010:9
  56:     0x7fa60c02d315 - std::sys::unix::thread::Thread::new::thread_start::h79fe093c0599c14c
                               at /rustc/d9c13cd4531649c2028a8384cb4d4e54f985380e/library/std/src/sys/unix/thread.rs:108:17
  57:     0x7fa60bd78b43 - <unknown>
  58:     0x7fa60be0aa00 - <unknown>
  59:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0-nightly (d9c13cd45 2023-07-05) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C incremental=[REDACTED] -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [specialization_graph_of] building specialization graph of trait `ops::Square`
#1 [coherent_trait] coherence checking all impls of trait `ops::Square`
#2 [analysis] running analysis passes on this crate
```

**Comment by Nashtare** [comment]
This is actually an issue with latest nightly toolchain which broke the build. Reverting to a prior version (e.g. nightly-2023-06-30 for instance) does the job.

**Comment by cyl19970726** [comment]
specify the version to solve this problem 
```
rustup toolchain install nightly-2023-06-29  
rustup override set nightly-2023-06-29-aarch64-apple-darwin  
```
